// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Adapter from "../Adapter.res.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";

let connected = {
  contents: false
};

async function runPulumiCmd(args) {
  return await $$Deno.Command.run("pulumi", args);
}

async function connect() {
  let match = await runPulumiCmd(["version"]);
  if (match[0] === 0) {
    connected.contents = true;
    return;
  } else {
    return Stdlib_Exn.raiseError("Pulumi CLI not found");
  }
}

async function disconnect() {
  connected.contents = false;
}

async function isConnected() {
  return connected.contents;
}

async function previewHandler(args) {
  let match = args["stack"];
  let stack = typeof match === "string" ? match : undefined;
  let match$1 = args["path"];
  let path = typeof match$1 === "string" ? match$1 : ".";
  let cmdArgs = [
    "preview",
    "--cwd",
    path,
    "--json"
  ];
  if (stack !== undefined) {
    cmdArgs.push(`--stack=` + stack);
  }
  let match$2 = await runPulumiCmd(cmdArgs);
  return Object.fromEntries([
    [
      "success",
      match$2[0] === 0
    ],
    [
      "output",
      match$2[1]
    ],
    [
      "error",
      match$2[2]
    ]
  ]);
}

async function upHandler(args) {
  let match = args["stack"];
  let stack = typeof match === "string" ? match : undefined;
  let match$1 = args["path"];
  let path = typeof match$1 === "string" ? match$1 : ".";
  let match$2 = args["yes"];
  let yes = match$2 === true;
  let cmdArgs = [
    "up",
    "--cwd",
    path,
    "--json"
  ];
  if (stack !== undefined) {
    cmdArgs.push(`--stack=` + stack);
  }
  if (yes) {
    cmdArgs.push("--yes");
  }
  let match$3 = await runPulumiCmd(cmdArgs);
  return Object.fromEntries([
    [
      "success",
      match$3[0] === 0
    ],
    [
      "output",
      match$3[1]
    ],
    [
      "error",
      match$3[2]
    ]
  ]);
}

async function destroyHandler(args) {
  let match = args["stack"];
  let stack = typeof match === "string" ? match : undefined;
  let match$1 = args["path"];
  let path = typeof match$1 === "string" ? match$1 : ".";
  let match$2 = args["yes"];
  let yes = match$2 === true;
  let cmdArgs = [
    "destroy",
    "--cwd",
    path,
    "--json"
  ];
  if (stack !== undefined) {
    cmdArgs.push(`--stack=` + stack);
  }
  if (yes) {
    cmdArgs.push("--yes");
  }
  let match$3 = await runPulumiCmd(cmdArgs);
  return Object.fromEntries([
    [
      "success",
      match$3[0] === 0
    ],
    [
      "output",
      match$3[1]
    ],
    [
      "error",
      match$3[2]
    ]
  ]);
}

async function stackListHandler(args) {
  let match = args["path"];
  let path = typeof match === "string" ? match : ".";
  let match$1 = await runPulumiCmd([
    "stack",
    "ls",
    "--cwd",
    path,
    "--json"
  ]);
  if (match$1[0] !== 0) {
    return Object.fromEntries([
      [
        "success",
        false
      ],
      [
        "error",
        match$1[2]
      ]
    ]);
  }
  let stdout = match$1[1];
  try {
    return JSON.parse(stdout);
  } catch (exn) {
    return Object.fromEntries([[
        "stacks",
        stdout
      ]]);
  }
}

async function stackSelectHandler(args) {
  let match = args["stack"];
  let stack = typeof match === "string" ? match : Stdlib_Exn.raiseError("stack parameter is required");
  let match$1 = args["path"];
  let path = typeof match$1 === "string" ? match$1 : ".";
  let match$2 = await runPulumiCmd([
    "stack",
    "select",
    stack,
    "--cwd",
    path
  ]);
  return Object.fromEntries([
    [
      "success",
      match$2[0] === 0
    ],
    [
      "stack",
      stack
    ],
    [
      "error",
      match$2[2]
    ]
  ]);
}

async function stackInitHandler(args) {
  let match = args["stack"];
  let stack = typeof match === "string" ? match : Stdlib_Exn.raiseError("stack parameter is required");
  let match$1 = args["path"];
  let path = typeof match$1 === "string" ? match$1 : ".";
  let match$2 = await runPulumiCmd([
    "stack",
    "init",
    stack,
    "--cwd",
    path
  ]);
  return Object.fromEntries([
    [
      "success",
      match$2[0] === 0
    ],
    [
      "stack",
      stack
    ],
    [
      "output",
      match$2[1]
    ],
    [
      "error",
      match$2[2]
    ]
  ]);
}

async function stackOutputHandler(args) {
  let match = args["stack"];
  let stack = typeof match === "string" ? match : undefined;
  let match$1 = args["path"];
  let path = typeof match$1 === "string" ? match$1 : ".";
  let cmdArgs = [
    "stack",
    "output",
    "--cwd",
    path,
    "--json"
  ];
  if (stack !== undefined) {
    cmdArgs.push(`--stack=` + stack);
  }
  let match$2 = await runPulumiCmd(cmdArgs);
  if (match$2[0] !== 0) {
    return Object.fromEntries([
      [
        "success",
        false
      ],
      [
        "error",
        match$2[2]
      ]
    ]);
  }
  let stdout = match$2[1];
  try {
    return JSON.parse(stdout);
  } catch (exn) {
    return Object.fromEntries([[
        "outputs",
        stdout
      ]]);
  }
}

async function refreshHandler(args) {
  let match = args["stack"];
  let stack = typeof match === "string" ? match : undefined;
  let match$1 = args["path"];
  let path = typeof match$1 === "string" ? match$1 : ".";
  let match$2 = args["yes"];
  let yes = match$2 === true;
  let cmdArgs = [
    "refresh",
    "--cwd",
    path,
    "--json"
  ];
  if (stack !== undefined) {
    cmdArgs.push(`--stack=` + stack);
  }
  if (yes) {
    cmdArgs.push("--yes");
  }
  let match$3 = await runPulumiCmd(cmdArgs);
  return Object.fromEntries([
    [
      "success",
      match$3[0] === 0
    ],
    [
      "output",
      match$3[1]
    ],
    [
      "error",
      match$3[2]
    ]
  ]);
}

async function configSetHandler(args) {
  let match = args["key"];
  let key = typeof match === "string" ? match : Stdlib_Exn.raiseError("key parameter is required");
  let match$1 = args["value"];
  let value = typeof match$1 === "string" ? match$1 : Stdlib_Exn.raiseError("value parameter is required");
  let match$2 = args["secret"];
  let secret = match$2 === true;
  let match$3 = args["path"];
  let path = typeof match$3 === "string" ? match$3 : ".";
  let cmdArgs = [
    "config",
    "set",
    key,
    value,
    "--cwd",
    path
  ];
  if (secret) {
    cmdArgs.push("--secret");
  }
  let match$4 = await runPulumiCmd(cmdArgs);
  return Object.fromEntries([
    [
      "success",
      match$4[0] === 0
    ],
    [
      "key",
      key
    ],
    [
      "error",
      match$4[2]
    ]
  ]);
}

async function configGetHandler(args) {
  let match = args["key"];
  let key = typeof match === "string" ? match : Stdlib_Exn.raiseError("key parameter is required");
  let match$1 = args["path"];
  let path = typeof match$1 === "string" ? match$1 : ".";
  let match$2 = await runPulumiCmd([
    "config",
    "get",
    key,
    "--cwd",
    path
  ]);
  return Object.fromEntries([
    [
      "success",
      match$2[0] === 0
    ],
    [
      "key",
      key
    ],
    [
      "value",
      match$2[1].trim()
    ],
    [
      "error",
      match$2[2]
    ]
  ]);
}

async function versionHandler(_args) {
  let match = await runPulumiCmd(["version"]);
  return Object.fromEntries([
    [
      "success",
      match[0] === 0
    ],
    [
      "version",
      match[1].trim()
    ],
    [
      "error",
      match[2]
    ]
  ]);
}

let tools = Object.fromEntries([
  [
    "pulumi_preview",
    {
      description: "Preview changes to infrastructure",
      params: Object.fromEntries([
        [
          "path",
          Adapter.stringParam("Path to Pulumi project")
        ],
        [
          "stack",
          Adapter.stringParam("Stack name to preview")
        ]
      ]),
      handler: previewHandler
    }
  ],
  [
    "pulumi_up",
    {
      description: "Deploy infrastructure changes",
      params: Object.fromEntries([
        [
          "path",
          Adapter.stringParam("Path to Pulumi project")
        ],
        [
          "stack",
          Adapter.stringParam("Stack name to deploy")
        ],
        [
          "yes",
          Adapter.boolParam("Skip confirmation prompt")
        ]
      ]),
      handler: upHandler
    }
  ],
  [
    "pulumi_destroy",
    {
      description: "Destroy infrastructure",
      params: Object.fromEntries([
        [
          "path",
          Adapter.stringParam("Path to Pulumi project")
        ],
        [
          "stack",
          Adapter.stringParam("Stack name to destroy")
        ],
        [
          "yes",
          Adapter.boolParam("Skip confirmation prompt")
        ]
      ]),
      handler: destroyHandler
    }
  ],
  [
    "pulumi_stack_list",
    {
      description: "List all stacks",
      params: Object.fromEntries([[
          "path",
          Adapter.stringParam("Path to Pulumi project")
        ]]),
      handler: stackListHandler
    }
  ],
  [
    "pulumi_stack_select",
    {
      description: "Select a stack",
      params: Object.fromEntries([
        [
          "stack",
          Adapter.stringParam("Stack name to select")
        ],
        [
          "path",
          Adapter.stringParam("Path to Pulumi project")
        ]
      ]),
      handler: stackSelectHandler
    }
  ],
  [
    "pulumi_stack_init",
    {
      description: "Create a new stack",
      params: Object.fromEntries([
        [
          "stack",
          Adapter.stringParam("Stack name to create")
        ],
        [
          "path",
          Adapter.stringParam("Path to Pulumi project")
        ]
      ]),
      handler: stackInitHandler
    }
  ],
  [
    "pulumi_stack_output",
    {
      description: "Get stack outputs",
      params: Object.fromEntries([
        [
          "stack",
          Adapter.stringParam("Stack name")
        ],
        [
          "path",
          Adapter.stringParam("Path to Pulumi project")
        ]
      ]),
      handler: stackOutputHandler
    }
  ],
  [
    "pulumi_refresh",
    {
      description: "Refresh state from cloud",
      params: Object.fromEntries([
        [
          "path",
          Adapter.stringParam("Path to Pulumi project")
        ],
        [
          "stack",
          Adapter.stringParam("Stack name")
        ],
        [
          "yes",
          Adapter.boolParam("Skip confirmation prompt")
        ]
      ]),
      handler: refreshHandler
    }
  ],
  [
    "pulumi_config_set",
    {
      description: "Set a configuration value",
      params: Object.fromEntries([
        [
          "key",
          Adapter.stringParam("Configuration key")
        ],
        [
          "value",
          Adapter.stringParam("Configuration value")
        ],
        [
          "secret",
          Adapter.boolParam("Encrypt the value")
        ],
        [
          "path",
          Adapter.stringParam("Path to Pulumi project")
        ]
      ]),
      handler: configSetHandler
    }
  ],
  [
    "pulumi_config_get",
    {
      description: "Get a configuration value",
      params: Object.fromEntries([
        [
          "key",
          Adapter.stringParam("Configuration key")
        ],
        [
          "path",
          Adapter.stringParam("Path to Pulumi project")
        ]
      ]),
      handler: configGetHandler
    }
  ],
  [
    "pulumi_version",
    {
      description: "Show Pulumi version",
      params: {},
      handler: versionHandler
    }
  ]
]);

let name = "pulumi";

let description = "Pulumi Infrastructure as Code";

export {
  connected,
  name,
  description,
  runPulumiCmd,
  connect,
  disconnect,
  isConnected,
  previewHandler,
  upHandler,
  destroyHandler,
  stackListHandler,
  stackSelectHandler,
  stackInitHandler,
  stackOutputHandler,
  refreshHandler,
  configSetHandler,
  configGetHandler,
  versionHandler,
  tools,
}
/* tools Not a pure module */
